TEXTS = {
    'en': {
        'select_language': 'Please select language:',
        'select_menu': 'Please select menu:',
        'selected_language': 'You have selected English language 🇬🇧',
        'third_menu_option': 'You selected the third menu option.',
        'fourth_menu_option': 'You selected the fourth menu option.',
        'next_action': '<b>Menu\n</b>Please select the next action:',
        'select_option': 'Please select an option:',
        'starting_low': 'Starting from low',
        'starting_high': 'Starting from high',
        'select_kb_item': 'To call up a menu or a language, you can select the corresponding menu items',
        'title': 'Title',
        'rating': 'Rating',
        'genres': 'Genres',
        'submenu_keyboard': ['Popular Now', 'By TMDB Rating', 'Use filters'],
        'menu_keyboard': ['Movies', 'Series', 'Randomizer', 'Saved'],
        'LANGUAGE_CODES': 'en-US',
        'select_genre': 'Select a genre',
        'filter_submenu': ['By genre', 'By year', 'By viewer rating', 'By rating', 'Search', 'Back'],
        'release_date_options': [
            "Before 1980",
            "1980-2000",
            "2000-2020",
            "After 2020",
            "Any"
        ],
        'filter_releaseDate_txt': 'Choose release date',
        'movies': 'Movies',
        'series': 'Series',
        'back': 'Back',
        'save': 'Save',
        'delete': 'Delete',
    },
    'ua': {
        'select_language': 'Будь ласка, виберіть мову:',
        'select_menu': 'Будь ласка, виберіть меню:',
        'selected_language': '<b>Ви обрали українську мову </b>🇺🇦',
        'third_menu_option': 'Ви обрали третю опцію меню.',
        'fourth_menu_option': 'Ви обрали четверту опцію меню.',
        'next_action': '<b>Меню\n</b>Будь ласка, виберіть наступну дію:',
        'select_option': 'Будь ласка, виберіть опцію:',
        'starting_low': 'Починаючи з низького',
        'starting_high': 'Починаючи з високого',
        'select_kb_item': 'Щоб викликати меню або мову, ви можете вибрати відповідні пункти меню',
        'title': 'Назва',
        'rating': 'Рейтинг',
        'genres': 'Жанри',
        'submenu_keyboard': ['Популярне зараз', 'За рейтингом TMDB', 'Використовувати фільтри'],
        'menu_keyboard': ['Фільми', 'Серіали', 'Рандомайзер', 'Збережені'],
        'LANGUAGE_CODES': 'uk-UA',
        'select_genre': 'Виберіть жанр',
        'filter_submenu': ['За жанром', 'За роком', 'За рейтингом глядачів', 'За рейтингом', 'Пошук', 'Назад'],
        'release_date_options': [
            "до 1980",
            "1980-2000",
            "2000-2020",
            "після 2020",
            "Без різниці"
        ],
        'filter_releaseDate_txt': 'Виберіть дату виходу',
        'movies': 'Фільми',
        'series': 'Серіали',
        'back': 'Назад',
        'save': 'Зберегти',
        'delete': 'Видалити'
    },
    'ru': {
        'select_language': 'Пожалуйста, выберите язык:',
        'select_menu': 'Пожалуйста, выберите меню:',
        'selected_language': 'Вы выбрали русский язык 🇷🇺',
        'third_menu_option': 'Вы выбрали третью опцию меню.',
        'fourth_menu_option': 'Вы выбрали четвертую опцию меню.',
        'next_action': '<b>Меню\n</b>Пожалуйста, выберите следующее действие:',
        'select_option': 'Пожалуйста, выберите опцию:',
        'starting_low': 'Начиная с низкого',
        'starting_high': 'Начиная с высокого',
        'select_kb_item': 'Для вызова меню или языка можно выбрать соответствующие пункты меню',
        'title': 'Название',
        'rating': 'Рейтинг',
        'genres': 'Жанры',
        'submenu_keyboard': ['Популярно сейчас', 'По рейтингу TMDB', 'Использовать фильтры'],
        'menu_keyboard': ['Фильмы', 'Сериалы', 'Рандомайзер', 'Сохраненные'],
        'LANGUAGE_CODES': 'ru-RU',
        'select_genre': 'Выберите жанр',
        'filter_submenu': ['По жанру', 'По году', 'По кол-во оценок', 'По рейтингу', 'Поиск', 'Назад'],
        'release_date_options': [
            "до 1980",
            "1980-2000",
            "2000-2020",
            "после 2020",
            "Без разницы"
        ],
        'filter_releaseDate_txt': 'Выберите дату выхода',
        'movies': 'Фильмы',
        'series': 'Сериалы',
        'back': 'Назад',
        'save': 'Сохранить',
        'delete': 'Удалить'
    },
}
