TEXTS = {
    'en': {
        'select_language': 'Please select language:',
        'select_menu': 'Please select menu:',
        'selected_language': 'You have selected English language 🇬🇧',
        'third_menu_option': 'You selected the third menu option.',
        'fourth_menu_option': 'You selected the fourth menu option.',
        'next_action': '<b>Menu\n</b>Please select the next action:',
        'select_option': 'Please select an option:',
        'starting_low': 'Starting from low',
        'starting_high': 'Starting from high',
        'select_kb_item': 'To call up a menu or a language, you can select the corresponding menu items',
        'title': 'Title',
        'rating': 'Rating',
        'genres': 'Genres',
        'submenu_keyboard': ['Popular Now', 'By TMDB Rating', 'By Genre', 'Use filters'],
        'menu_keyboard': ['Movies', 'Series', 'Randomizer', 'Saved'],
        'LANGUAGE_CODES': 'en-US',
    },
    'ua': {
        'select_language': 'Будь ласка, виберіть мову:',
        'select_menu': 'Будь ласка, виберіть меню:',
        'selected_language': '<b>Ви обрали українську мову </b>🇺🇦',
        'third_menu_option': 'Ви обрали третю опцію меню.',
        'fourth_menu_option': 'Ви обрали четверту опцію меню.',
        'next_action': '<b>Меню\n</b>Будь ласка, виберіть наступну дію:',
        'select_option': 'Будь ласка, виберіть опцію:',
        'starting_low': 'Починаючи з низького',
        'starting_high': 'Починаючи з високого',
        'select_kb_item': 'Щоб викликати меню або мову, ви можете вибрати відповідні пункти меню',
        'title': 'Назва',
        'rating': 'Рейтинг',
        'genres': 'Жанри',
        'submenu_keyboard': ['Популярне зараз', 'За рейтингом TMDB', 'За жанром', 'Використовувати фільтри'],
        'menu_keyboard': ['Фільми', 'Серіали', 'Рандомайзер', 'Збережені'],
        'LANGUAGE_CODES': 'uk-UA',
    },
    'ru': {
        'select_language': 'Пожалуйста, выберите язык:',
        'select_menu': 'Пожалуйста, выберите меню:',
        'selected_language': 'Вы выбрали русский язык 🇷🇺',
        'third_menu_option': 'Вы выбрали третью опцию меню.',
        'fourth_menu_option': 'Вы выбрали четвертую опцию меню.',
        'next_action': '<b>Меню\n</b>Пожалуйста, выберите следующее действие:',
        'select_option': 'Пожалуйста, выберите опцию:',
        'starting_low': 'Начиная с низкого',
        'starting_high': 'Начиная с высокого',
        'select_kb_item': 'Для вызова меню или языка можно выбрать соответствующие пункты меню',
        'title': 'Название',
        'rating': 'Рейтинг',
        'genres': 'Жанры',
        'submenu_keyboard': ['Популярно сейчас', 'По рейтингу TMDB', 'По жанру', 'Использовать фильтры'],
        'menu_keyboard': ['Фильмы', 'Сериалы', 'Рандомайзер', 'Сохраненные'],
        'LANGUAGE_CODES': 'ru-RU',
    },
}
